name: Build fine with input test

on:
  workflow_call:
    inputs:
      custom:
        description: Some custom string
        required: true
        type: string

jobs:
  test1:
    name: ðŸ§ª Test1
    uses: ./.github/workflows/app-custom-name1.yml
  
  test2:
    name: ðŸ§ª Test2
    uses: ./.github/workflows/app-custom-name2.yml

  # test-custom:
  #   name: ðŸ§ª Test Custom
  #   uses: ./.github/workflows/app-${{ inputs.custom }}.yml
  
  test-print:
    runs-on: ubuntu-latest
    name: Print input
    steps:
      - name: Step print string
        run: echo "Hello"
        
      - name: Step print inputs
        run: echo ${{ inputs.custom }}
 